### ISSUE TITLE
Controller button names/default assignment confusing

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [PMDCollab/PMDC#10]
A collection of several smaller issues related to gamepad control displays:

### Button names
Gamepad buttons are always named according to Xbox controller layout, e.g. the face button on the right is always called `(B)` (excluding the triggers, which are called `(RightTrigger)` and `(LeftTrigger)` instead of `(RT)` and `(LT)`). This is especially confusing for Nintendo Switch controller users, who have `(A)` as the right face button.

### Default assignment
By default, the right face button is always assigned as Confirm and the bottom face button as Cancel. This is confusing to Xbox and Playstation controller users, as they are used to the bottom face button (`(A)`/`(X)`) being the confirm button and the right face button (`(B)`/`(O)`) being the cancel button.

### Ideal behavior
* The default confirm/attack button on Nintendo and Xbox controllers is `(A)`, despite their different location. The default confirm/attack button on Playstation controllers is `(X)`.
* The default cancel/run button on Nintendo and Xbox controllers is `(B)`, despite their different location. The default cancel/run button on Playstation controllers is `(O)`.
* The default menu button on Nintendo controllers is `(X)`, to match the original games.
* Secondary buttons such as the trigger and menu buttons should use the names each controller gives them as well.
* When holding `(ZL)`/`(LT)`/`(L2)`, the layout of moves should always match the face buttons' location by default.
* The labels for what button a player should press to take a certain action should always match the currently-plugged-in controller.

**Comment by audinowho** [comment]
Fixed as of https://github.com/RogueCollab/RogueEssence/commit/89cab76fb0668769df1694aaa182e67f7216f8b5
